### PR TITLE
Feature/507 fix state update warning

### LINKED ISSUE #507: Warning displayed in Set Identity Screen
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in ModalizeBase (at IdentityGuideScreen.tsx:21)
    in IdentityGuideScreen (at SceneView.tsx:126)
    in StaticContainer
    in EnsureSingleNavigator (at SceneView.tsx:118)
    in SceneView (at useDescriptors.tsx:209)
    in RCTView (at View.js:32)
    in View (at CardContainer.tsx:280)
    in RCTView (at View.js:32)
    in View (at CardContainer.tsx:278)
    in RCTView (at View.js:32)
    in View (at CardSheet.tsx:33)
    in CardSheet (at Card.tsx:557)
    in RCTView (at View.js:32)
    in View (at createAnimatedComponent.js:243)
    in AnimatedComponent (at createAnimatedComponent.js:296)
    in AnimatedComponentWrapper (at Card.tsx:536)
    in PanGestureHandler (at GestureHandlerNative.tsx:14)
    in PanGestureHandler (at Card.tsx:530)
    in RCTView (at View.js:32)
    in View (at createAnimatedComponent.js:243)
    in AnimatedComponent (at createAnimatedComponent.js:296)
    in AnimatedComponentWrapper (at Card.tsx:526)
    in RCTView (at View.js:32)
    in View (at Card.tsx:520)
    in Card (at CardContainer.tsx:218)
    in CardContainer (at CardStack.tsx:649)
    in RNSScreen (at createAnimatedComponent.js:243)
    in AnimatedComponent (at createAnimatedComponent.js:296)
    in AnimatedComponentWrapper (at src/index.native.tsx:171)
    in Screen (at Screens.tsx:37)
    in MaybeScreen (at CardStack.tsx:642)

### PR DESCRIPTION
**Pull request by ahoseinian**
Fix state update warning and minor improvements

fixes #507

### CODE REVIEW

File: src/screen/AddAccountScreen/AddAccountScreen.tsx [hunk 1]
```diff
@@ -80,14 +80,14 @@ export function AddAccountScreen({navigation}: {navigation: NavigationProp<AppSt
...
-      withOverlay={true}
-      threshold={250}
-      scrollViewProps={{showsVerticalScrollIndicator: false}}
       adjustToContentHeight
-      onClose={navigation.goBack}
-      handlePosition="outside"
+      onClose={() => {
+        // timeout fixes a warning about animation event handling
+        // not sure what is the problem
+        setTimeout(navigation.goBack, 0);
```
Comment (silva-fj) [inline src/screen/AddAccountScreen/AddAccountScreen.tsx:87]: Is the issue only happening in this screen? We are doing the same in some other places

**Review by silva-fj — DISMISSED** [review]

File: src/screen/AddAccountScreen/AddAccountScreen.tsx (hunk 1 above)
Comment (ahoseinian) [reply src/screen/AddAccountScreen/AddAccountScreen.tsx:87]: yes, I saw it only here. for example on `MyIdentity` screen and `DevScreen` it was fine.

**Review by silva-fj — APPROVED** [review]
