### PR TITLE
Fixing BlockTime component

### LINKED ISSUE #181: Bug: `undefined undefined` on Tip detail screen
App version:
Latest build on Bitrise

## Steps To Reproduce

1. Navigate to Tip detail screen

PS. not all of them have this issue. In screenshot there is one attached.

Link or media file of the bug:

## The current behavior
showing `undefined undefined`

## The expected behavior
should show either nothing or give meaningful info

IMG_2603

### PR DESCRIPTION
**Pull request by silva-fj**
This will allow the component to display the correct time, including not just day and hours but also minutes and seconds when appropriate. Fixes #181

### CODE REVIEW

File: src/layout/BlockTime.tsx [hunk 1]
```diff
@@ -19,6 +19,13 @@ const styles = StyleSheet.create({
 
 export function BlockTime({blockNumber}: Props) {
   const {timeStringParts} = useBlockTime(blockNumber);
```
Comment (ahoseinian) [inline src/layout/BlockTime.tsx:21]: should we destruct it to make it more readable?
```suggestion
  const {timeStringParts} = useBlockTime(blockNumber);
  const [days, hours, minutes, seconds] = timeStringParts;
```

**Review by ahoseinian — DISMISSED** [review]

**Review by ahoseinian — DISMISSED** [review]

**Review by ahoseinian — APPROVED** [review]
