### PR TITLE
UI-bug-fix

### LINKED ISSUE #1127: Bug: UI-display-fix

### PR DESCRIPTION
**Pull request by Ekaanth**
UI fixed

### CODE REVIEW

File: src/ui/screens/AddAccountScreen/AddressPreview.tsx [hunk 1]
```diff
@@ -53,27 +55,29 @@ function AddressInfoPreview(props: PropTypes) {
...
-                      key={i}
-                      registrationJudgement={judgment}
-                      hasParent={Boolean(accountInfo?.registration?.displayParent)}
-                    />
-                  );
-                }
-              })
-            }
-          />
+          {accountInfo?.registration?.judgements && accountInfo?.registration?.judgements.length > 0 ? (
```
Comment (ishrak-imam) [inline src/ui/screens/AddAccountScreen/AddressPreview.tsx]: Instead of completely removing let's give the information `No judgements provided`

**Review by ishrak-imam — APPROVED** [review]

**Review by silva-fj — APPROVED** [review]
