### PR TITLE
Fixing unstable nested components warning

### LINKED ISSUE #1199: Bug: Fix react/no-unstable-nested-components
Currently the warning `react/no-unstable-nested-components` is turned off in `.eslintrc.js`

Adjust the code to fix the warning and enable the eslint rule.

### PR DESCRIPTION
**Pull request by ishrak-imam**
### Description

Fixes: #1199 

Fixing the warnings that resulted from [this eslint rule](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/no-unstable-nested-components.md) and turning the rule from warning to error so that we don't replicate this again.

### CODE REVIEW

File: src/ui/components/Account/AddressPreview.tsx [hunk 1]
```diff
@@ -8,12 +8,18 @@ import {useAccount} from 'src/api/hooks/useAccount';
...
+import {isString} from 'lodash';
 
 type PropTypes = {
   address: string;
 };
 
-function AddressInfoPreview(props: PropTypes) {
+const ItemLeft = (children: React.ReactNode) => () => <View style={globalStyles.justifyCenter}>{children}</View>;
+
+const ItemRight = (children: string | React.ReactNode) => () =>
```
Comment (silva-fj) [inline src/ui/components/Account/AddressPreview.tsx]:
```suggestion
const ItemRight = (children: React.ReactNode) => () =>
```

File: src/ui/components/Account/AddressPreview.tsx [hunk 2]
```diff
@@ -8,12 +8,18 @@ import {useAccount} from 'src/api/hooks/useAccount';
...
+  <View style={globalStyles.justifyCenter}>{isString(children) ? <Caption>{children}</Caption> : children}</View>;
```
Comment (silva-fj) [inline src/ui/components/Account/AddressPreview.tsx]: NIT: You can also do `typeof children === 'string'`

**Review by silva-fj — APPROVED** [review]
