### PR TITLE
Issue 898 enable notification after disable

### LINKED ISSUE #898: Bug: can't enable notifications after disabling
> I can't enable notifications after initially disabling them. It works if you reinstall, but I think that might be a bug. 

Get this feedback from Raul, confirmation needed.

App version:

## Steps To Reproduce

1.
2.

Link or media file of the bug:

### PR DESCRIPTION
**Pull request by Ekaanth**
On the suggestion of @franjs from https://github.com/litentry/litentry-app/pull/903#issuecomment-1047881167 
this is a new PR, while closing the previous [PR](https://github.com/litentry/litentry-app/pull/903) 
Simulator Screen Shot - iPhone 12 - 2022-02-23 at 13 25 47

### CODE REVIEW

File: src/hooks/useUpdatePushAuthorizationStatus.ts [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+export function useUpdatePushAuthorizationStatus(): void {
+  const queryClient = useQueryClient();
+  const {didAppCameToForeground} = useAppState();
+
+  useEffect(() => {
+    (async () => {
+      if (didAppCameToForeground) {
+        queryClient.invalidateQueries('push_authorization_status');
+      }
+    })();
```
Comment (ishrak-imam) [inline src/hooks/useUpdatePushAuthorizationStatus.ts]: Why did you need to use `async` here and why this part is inside an IIFE?

File: src/ui/navigation/AppNavigator.tsx [hunk 2]
```diff
@@ -250,7 +250,7 @@ function AppNavigator() {
     <AppStack.Navigator screenOptions={overlayScreenOptions}>
       {isPnPromptNeeded ? (
         <AppStack.Screen name={routeKeys.permissionGrantingPromptScreen}>
-          {() => <PermissionGrantingPrompt skipPnPermission={skipPnPermission} />}
+          {() => <PermissionGrantingPrompt skipPnPermission={skipPnPermission} isSkip={false} />}
```
Comment (ishrak-imam) [inline src/ui/navigation/AppNavigator.tsx]: You can make the `isSkip` optional in the component and pass it only when necessary.

File: src/ui/screens/PermissionGrantingPrompt.tsx [hunk 3]
```diff
@@ -8,10 +8,11 @@ import {Caption, Headline, Button, useTheme, Subheading, Icon} from '@ui/library
 import {Layout} from '@ui/components/Layout';
 
 type Props = {
-  skipPnPermission: () => void;
+  skipPnPermission?: () => void;
+  isSkip: boolean;
 };
 
-function PermissionGrantingPromptScreen({skipPnPermission}: Props) {
+function PermissionGrantingPromptScreen({skipPnPermission, isSkip}: Props) {
```
Comment (ishrak-imam) [inline src/ui/screens/PermissionGrantingPrompt.tsx]: And here you can set a default value like `isSkip = false`. So when `isSkip` is `undefined` it will take the default value.

File: src/ui/screens/NotificationSettingsScreen.tsx [hunk 4]
```diff
@@ -8,13 +8,52 @@ import {usePushTopics} from '@hooks/usePushTopics';
...
+        {text: 'OK', onPress: openAppSetting},
+      ]);
+    }
+    if (permissionAllowed(pushAuthorizationStatus)) {
+      setSwitchDisabled(false);
+    }
+  }, [pushAuthorizationStatus, unSubscribeToAllTopics]);
+
+  if (hasPermissionsNotDetermined(pushAuthorizationStatus)) {
+    return <PermissionGrantingPrompt isSkip={true} />;
```
Comment (ishrak-imam) [inline src/ui/screens/NotificationSettingsScreen.tsx]: The `isSkip` name is confusing. The behaviour we want is to control the rendering of the Skip button.
`allowSkip={false}` and default value for `allowSkip` set to `true` in the component would make the readability better.

File: src/ui/navigation/AppNavigator.tsx [hunk 5]
```diff
@@ -250,7 +250,7 @@ function AppNavigator() {
     <AppStack.Navigator screenOptions={overlayScreenOptions}>
       {isPnPromptNeeded ? (
         <AppStack.Screen name={routeKeys.permissionGrantingPromptScreen}>
-          {() => <PermissionGrantingPrompt skipPnPermission={skipPnPermission} />}
+          {() => <PermissionGrantingPrompt skipPnPermission={skipPnPermission} allowSkip={true} />}
```
Comment (ishrak-imam) [inline src/ui/navigation/AppNavigator.tsx]: Let's remove the `allowSkip` prop from here and set the default value to `true` in the component.

File: src/ui/screens/NotificationSettingsScreen.tsx [hunk 6]
```diff
@@ -32,18 +63,36 @@ export function NotificationSettingsScreen({}: PropTypes) {
...
-        </View>
-        <View style={styles.infoContainer}>
-          <Icon name="information-outline" />
-          <Padder scale={1} />
-          <Text>Don't forget to enable notifications in your phone's settings</Text>
+          {!permissionAllowed(pushAuthorizationStatus) && (
+            <View style={styles.container}>
+              <View style={styles.infoContainer}>
+                <View
+                  style={{...globalStyles.rowContainer, ...globalStyles.alignCenter, ...globalStyles.justifyCenter}}>
```
Comment (ishrak-imam) [inline src/ui/screens/NotificationSettingsScreen.tsx]: You don't need to spread the objects here. You can use the array syntax `style={[styleObject0, styleObject1]}`

File: src/ui/screens/NotificationSettingsScreen.tsx [hunk 7]
```diff
@@ -32,18 +63,36 @@ export function NotificationSettingsScreen({}: PropTypes) {
...
+                  <Headline style={styles.headline}>Turn on notifications?</Headline>
+                </View>
+                <Subheading>
+                  <Caption style={{...globalStyles.textCenter}}>
```
Comment (ishrak-imam) [inline src/ui/screens/NotificationSettingsScreen.tsx]: Same here, no need to spread and put it in an object again. You can just do `style={styleObject}`

**Review by ishrak-imam — APPROVED** [review]
Apart from the comments LGTM!
Great work.
