### PR TITLE
Disable none clickables

### LINKED ISSUE #228: Bug: None clickable elements are shown as clickable
As a User when I click on an element and that there is an effect I expect something to happen. 

## Steps To Reproduce

1. Go on the Dashboard 
2. Under "Council" tap on the left side box

Link or media file of the bug:

## The current behavior
There is a shadow effect

## The expected behavior
It shouldn't do anything as it is not a button but just an information box

Same for the left side box and the bottom box under "Treasury"

### PR DESCRIPTION
**Pull request by ahoseinian**
resolves #228

### Description
- disable none clickable cards

### CODE REVIEW

File: src/screen/Council/MotionsScreen.tsx [hunk 1]
```diff
@@ -16,24 +16,29 @@ import SafeView, {noTopEdges} from 'presentational/SafeView';
...
-        }}
-        ItemSeparatorComponent={Divider}
-        keyExtractor={(item) => item.hash.toHex()}
-        ListEmptyComponent={EmptyView}
-      />
+      {isLoading ? (
+        <LoadingView />
+      ) : (
+        <FlatList
+          refreshing={isLoading}
```
Comment (silva-fj) [inline src/screen/Council/MotionsScreen.tsx]: This can be removed

**Review by silva-fj — DISMISSED** [review]

File: src/screen/Council/MotionsScreen.tsx (hunk 1 above)
Comment (ahoseinian) [reply src/screen/Council/MotionsScreen.tsx]: I changed it with `isFetching` to show the loading indicator on swipe down

**Review by silva-fj — APPROVED** [review]

**Comment by geastwood** [comment]
Rebase and mergeable. 👯
