### PR TITLE
1328 bug unable to reconnect to the web socket

### LINKED ISSUE #1328: Bug: unable to reconnect to the web socket.
## Steps To Reproduce

1. Turn off the internet connection data and we see the globe in `Network switch` being disabled
2. Turn on the internet connection, The globe is still disabled.

Link or media file of the bug:

## The expected behavior
The WebSocket has to reconnect and the globe has to go back to normal.

### PR DESCRIPTION
**Pull request by Ekaanth**
fixed #1328 

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1202777006571904

### CODE REVIEW

**Comment by Ekaanth** [comment]
We can probably add connecting or loading when the network is in connecting state. Because we have only two states now, ready or not ready. But we have other network states too. What do you say, @ishrak-imam @franjs

File: src/polkadotApi/PolkadotApiWebView.tsx [hunk 1]
```diff
@@ -279,13 +280,14 @@ function useKeyringUtils(isWebviewLoaded: boolean, postMessage: PostMessage, res
 function useInitApi(isWebviewLoaded: boolean, postMessage: PostMessage) {
   const {currentNetwork} = useNetwork();
   const setApiState = useSetRecoilState(apiStatusState);
+  const {isConnected} = useNetInfo();
 
   React.useEffect(() => {
     if (isWebviewLoaded) {
```
Comment (ishrak-imam) [inline src/polkadotApi/PolkadotApiWebView.tsx]:
```suggestion
    if (isWebviewLoaded && isConnected) {
```

**Review by ishrak-imam — APPROVED** [review]
