### PR TITLE
Issue 1057 validation of forms in the app

### LINKED ISSUE #1057: Validation of forms in the app
- [ ] Go through all the forms and identify where it's needed
- [ ] Add validation to these places

### LINKED ISSUE #1069: Bug: Accounts screen unable to scroll
On click of any account details, unable to scroll.

## Steps To Reproduce

1. click on any user to redirect to the account screen
2. unable to scroll to balance card and account roles.

### PR DESCRIPTION
**Pull request by Ekaanth**
fixed #1069 and #1057 

Council screen:

crowdloan screen:

Referendum model

### CODE REVIEW

File: src/ui/screens/Council/CouncilScreen.tsx [hunk 1]
```diff
@@ -229,7 +231,12 @@ function CouncilVoteModal({visible, setVisible, candidates, moduleElection}: Cou
       : noop;
   };
 
-  const disabled = !amount || !account || selectedCandidates.length === 0;
+  const isValidEnteredBalance = useMemo(() => {
```
Comment (ishrak-imam) [inline src/ui/screens/Council/CouncilScreen.tsx]: Nit 💅 
```suggestion
  const isEnteredBalanceValid = useMemo(() => {
```

**Review by ishrak-imam — APPROVED** [review]
LGTM

**Comment by Ekaanth** [comment]
Update :

File: src/ui/components/SubmitProposal.tsx [hunk 2]
```diff
@@ -29,7 +32,13 @@ export function SubmitProposal() {
     dispatch({type: 'RESET'});
   };
 
-  const isDisabled = !state.account || !state.preimageHash || !state.balance;
+  const enteredBalance = stringToBn(state.balance ?? '0') ?? BN_ZERO;
```
Comment (silva-fj) [inline src/ui/components/SubmitProposal.tsx:35]: Why do you need to add `?? BN_ZERO` ? `stringToBn` returns `BN`

File: src/ui/components/SubmitProposal.tsx [hunk 3]
```diff
@@ -29,7 +32,13 @@ export function SubmitProposal() {
...
+  const democracyMinimumDeposit = formattedStringToBn(chainInfo?.democracyMinimumDeposit ?? '0') ?? BN_ZERO;
```
Comment (silva-fj) [inline src/ui/components/SubmitProposal.tsx]: Same here

**Review by silva-fj — APPROVED** [review]
Good work 👍🏼

File: src/ui/components/SubmitProposal.tsx (hunk 2 above)
Comment (Ekaanth) [reply src/ui/components/SubmitProposal.tsx:35]: in this case `state.balance` return string | undefined despite it being set to string. since I'm not comparing the value of undefined so I used `??` to handle the undefined cases.

Comment (silva-fj) [reply src/ui/components/SubmitProposal.tsx:35]: I understand that `state.balance` can be `undefined`, but the result of` stringToBn(state.balance ?? '0') ` would not be `undefined`, so `?? BN_ZERO` should not be needed.

Comment (Ekaanth) [reply src/ui/components/SubmitProposal.tsx:35]: The result from `stringToBn` returns `BN` or `undefined`, thereby I had to do it like that. in another case, `formattedStringToBn` returns only `BN` I fixed for that one.

Comment (silva-fj) [reply src/ui/components/SubmitProposal.tsx:35]: How can `stringToBn` return `undefined`? Here is the definition: 

`export function stringToBn(registry: Registry, input: string): BN `

Comment (Ekaanth) [reply src/ui/components/SubmitProposal.tsx:35]: In this case, I'm using `stringToBn` from the `useFormatBalance` hook and not from Utils, but under the hood, it uses the `StringToBn` from utils.

Comment (silva-fj) [reply src/ui/components/SubmitProposal.tsx:35]: Got it

**Review by silva-fj — APPROVED** [review]
