### PR TITLE
Council vote on Motions Issue-1009

### LINKED ISSUE #1009: Bug: Council member can not vote Aye/Nay in motion
## Steps To Reproduce

1. Add a council member account into the app
2. Try to vote Aye/Nay for any motion

## The current behaviour
Nothing happens

## The expected behaviour
Should start the TX

### PR DESCRIPTION
**Pull request by ishrak-imam**
### Description

Fixes #1009 

https://user-images.githubusercontent.com/16683923/160119882-0325d74d-ac88-42f7-b000-c550ca46a58e.mp4

Additionally this PR includes some code clean-up. Removing unused hooks.

### CODE REVIEW

**Review by Ekaanth — APPROVED** [review]

File: src/ui/components/SelectCouncilAccount.tsx [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+type Props = {
+  onSelect: (account: SelectedAccount) => void;
+};
+
+type SelectedAccount = {
+  account: AccountType;
+  accountInfo?: SubstrateChainAccount;
+};
+
+export function SelectCouncilAccount({onSelect}: Props) {
```
Comment (silva-fj) [inline src/ui/components/SelectCouncilAccount.tsx]: This component is doing the same as `SelectAccount`,  let's add a new prop `accounts` to `SelectAccount` and remove this one

File: src/ui/components/SelectRegistrar.tsx [hunk 2]
```diff
@@ -79,7 +79,7 @@ type RegistrarItemProps = {
 };
 
 function RegistrarItem({onSelect, registrar}: RegistrarItemProps) {
```
Comment (silva-fj) [inline src/ui/components/SelectRegistrar.tsx:81]: I've just realized we are doing the same in multiple places, I'll create an issue to refactor a bit all these components. We already have a `Select` component, we just need to make it a bit more generic to reuse it in all these cases

**Review by silva-fj — APPROVED** [review]
