### PR TITLE
1330 bug unable to refetch the data when fetching from graph fails

### LINKED ISSUE #1330: Bug: Unable to refetch the data when fetching from graph fails
## Steps To Reproduce

1. Turn off the internet connection, and we see the data that was fetching fails
2. on reconnecting to the internet, the re-fetching of data isn't happening.
3. only after refreshing the app does the data seem to be loading.

Link or media file of the bug:

## The expected behavior
The application data needs to be fetched as soon as the mobile is connected to the internet.

### PR DESCRIPTION
**Pull request by Ekaanth**
fixed #1330 

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1202775146405616

### CODE REVIEW

**Comment by Ekaanth** [comment]
Follow up TODO: https://app.asana.com/0/1202739194556156/1202805065193803

File: src/hooks/useNetInfo.ts [hunk 1]
```diff
@@ -2,7 +2,7 @@ import NetInfo from '@react-native-community/netinfo';
 import {useEffect, useState} from 'react';
 
 export function useNetInfo() {
-  const [isConnected, setIsConnected] = useState(false);
+  const [isConnected, setIsConnected] = useState(true);
```
Comment (ishrak-imam) [inline src/hooks/useNetInfo.ts]: Why would we want to set the initial state to`true`. In any case the initial state should be `false`. Is this fix related to the current scope of the bug?

File: src/ui/components/ScrollViewRefetch.tsx [hunk 2]
```diff
@@ -12,8 +13,13 @@ type Props = Omit<ScrollViewProps, 'refreshControl'> & {
 
 export function ScrollViewRefetch({children, refetchQueries, ...props}: Props) {
   const {colors} = useTheme();
+  const {isConnected} = useNetInfo();
   const {refreshing, refetch} = useRefetch(refetchQueries);
 
+  useEffect(() => {
+    refetch();
+  }, [isConnected, refetch]);
+
```
Comment (ishrak-imam) [inline src/ui/components/ScrollViewRefetch.tsx]: This would be an incorrect place to implement this behaviour. The `ScrollViewRefetch` component is supposed to handle the pull to refresh only. New responsibilities are added to the component which are unrelated.

Another approach can look something like following.

```
function useApiRefetch() {
    const {isConnected} = useNetInfo();
    const {refetch} = useRefetch();

    useEffect(() => {
      if(isConnected){
        refetch();
      }
    }, [isConnected, refetch]);
}
```
And use this `useApiRefetch()` hook somewhere high up in the component chain. such as in the `AppNavigator` component.

**Review by ishrak-imam — APPROVED** [review]
Is the behaviour tested in both platforms? Let me know if I can help in iOS testing.

**Comment by Ekaanth** [comment]
Please verify this on IOS, On android it works fine.

**Review by ishrak-imam — APPROVED** [review]
Works on iOS.
