### PR TITLE
Bug-1100-app-crash

### LINKED ISSUE #1100: Bug: App crashes when clicked on democracy.
When clicked on democracy 

## Steps To Reproduce

1. Click on democracy on the network which has referendums
2. The app crashes.

Link or media file of the bug:

https://user-images.githubusercontent.com/22363352/163836233-8b017631-f4e3-46bc-bb01-b75809297b6f.mp4

### PR DESCRIPTION
**Pull request by Ekaanth**
fixes #1100 

issue-1100

### CODE REVIEW

File: src/ui/components/ProposalCall.tsx [hunk 1]
```diff
@@ -55,12 +55,14 @@ function SubCall({subCall}: SubCallProps) {
...
     <Card mode="outlined" style={styles.subCallContainer}>
       <Card.Content>
-        {subCall.meta && (
-          <>
-            <Paragraph>{subCall.meta}</Paragraph>
-            <Padder scale={0.5} />
-          </>
-        )}
+        <Text>
+          {subCall.meta && (
```
Comment (silva-fj) [inline src/ui/components/ProposalCall.tsx]: This is not safe in react native, it is better to use `{subCall.meta ? <>...</> : null}`. I will add an eslint plugin to avoid this in a separate PR.

Comment (silva-fj) [reply src/ui/components/ProposalCall.tsx]: Yo can remove the `Text` wrapper

**Review by silva-fj — APPROVED** [review]
Well, it looks that there is a plugin for this but it does not seem to work.. 

We can do: `{something ? <Component /> : null}` or `{!!something && <Component />}`. Just be aware of this issue in react native, `0` or `''` or `NaN` will crash the app when using `&&`.
