### PR TITLE
issue-1342: closeExternalAccount manually

### LINKED ISSUE #1342: Bug: Add external account bottom sheet open.
## Steps To Reproduce

1. Press on add external account
2. Add an external account via QR or type-in
3. and press confirm => press confirm and press close.
4. Press on the added account and press back button
5. add external account bottom sheet is still open.

Link or media file of the bug:

## The expected behavior

The bottom sheet has to be closed when we return to my accounts page.

### PR DESCRIPTION
**Pull request by Ekaanth**
fixed #1342 

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1202837001479663

### CODE REVIEW

File: src/ui/screens/AccountsScreen.tsx [hunk 1]
```diff
@@ -56,7 +56,8 @@ export function AccountsScreen({navigation}: Props) {
     navigation.setOptions({
       headerRight: HeaderRight,
     });
-  }, [navigation, HeaderRight]);
+    closeExternalAccount();
```
Comment (silva-fj) [inline src/ui/screens/AccountsScreen.tsx:60]: Please, double check that there are not other issues introduced with this. Also, can you create an issue and add a TODO here with the link to keep track of it (If the library fixes the bug this should be removed)

Comment (Ekaanth) [reply src/ui/screens/AccountsScreen.tsx:60]: Ok, I'll verify that and add a TODO in the next commit.

**Review by silva-fj — APPROVED** [review]
